- platform: ping
  name: macbook
  host: !secret mac_ip

- platform: workday
  country: UK

- platform: mqtt
  name: "Wipy water monitor"
  state_topic: "bme680-water"

- platform: mqtt
  name: "Elgato_Door"
  state_topic: "elgato_door"

- platform: mqtt
  name: "Fibaro_leak"
  state_topic: "fibaro_leak"

- platform: rest
  scan_interval: 1
  resource: http://192.168.0.28:8123/api/states/binary_sensor.front_door
  name: front_door
  value_template: '{{value_json.state}}'

- platform: template
  sensors:
    kettle_warm:
      value_template: >-
        {{ is_state("timer.kettle", "active") }}

- platform: template
  sensors:
    motion_at_home:
      value_template: >-
        {%- if is_state("sensor.hall_motion_sensor", "on")
        or is_state("sensor.living_room_motion_sensor", "on")
        or is_state("sensor.bedroom_motion_sensor", "on")
            -%}
        True
        {%- else -%}
        False
        {%- endif %}

- platform: template
  sensors:
    late_night_sensor:
      value_template: >-
          {{ strptime("22:00", "%H%M")  < now().strftime("%H:%M")
             or now().strftime("%H:%M") < strptime("07:00", "%H%M") }}


- platform: template
  sensors:
    devices_home:
      value_template: >-
        {{ is_state("group.all_devices", "home") }}

- platform: threshold
  name: 'Kettle'
  entity_id: sensor.wemo_current_power_w
  upper: 20

- platform: 'bayesian'
  name: 'in_bed_bayesian'
  prior: 0.25
  observations:
    - entity_id: 'input_boolean.house_idle'
      prob_given_true: 0.6
      platform: 'state'
      to_state: 'on'
    - entity_id: 'binary_sensor.late_night_sensor'
      prob_given_true: 0.8
      platform: 'state'
      to_state: 'on'
    - entity_id: 'binary_sensor.motion_at_home'
      prob_given_true: 0.1
      platform: 'state'
      to_state: 'on'
    - entity_id: 'switch.macbook_power'
      prob_given_true: 0.1
      platform: 'state'
      to_state: 'on'
    - entity_id: 'switch.tv'
      prob_given_true: 0.1
      platform: 'state'
      to_state: 'on'
